---
title: "New Story & Tweet Update"
author: "Jason Neumeyer"
date: "2/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## NEW STORY

William Hall | [Fox News/MSNBC] 

The latest report released using U.S. Census Bureau data states that immigrant-owned businesses employed over 8 million workers in fiscal year 2019, up from 2018 totals. These businesses also experienced an increase in the total amount of sales revenue, which rose to almost $1.3 trillion during the same period. It is all but guaranteed that these numbers will decline in 2020 resulting from the COVID-19 pandemic; however, if the economy is to regain its pre-pandemic success, small businesses, including many of these new immigrant-owned businesses, will need to be the driving force behind the resurgence.

Figure 4: Percent of Immigrant Entrepreneurs 

The high-water mark for immigrant-owned business in 2019 was borne out of hundreds of success stories across many different sectors of the economy, especially the service industry. Eduardo Rodriguez, a 62-year-old immigrant living in the Little Village neighborhood of Chicago, is a perfect example of this success. In an area of the city that has an unemployment rate of 13 percent and an annual median income of $30,000–less than half of the national average–the Little Village community faces considerable economic challenges. However, these conditions have not stopped Rodriguez. He currently owns and operates four Dulcelandia stores in Little Village, each one packed with over 1,000 types of delicious candies from his home country of Mexico. After immigrating here in 1966, Rodriguez opened his first store and it became an instant gathering spot in the neighborhood. “People seem to really like what we are doing, and I’m grateful that I had the opportunity to do this in the United States. It takes a lot of work and sacrifice – we’re fulfilling a niche market that people really want to buy from.” 

Following in her father’s footsteps, Rodriguez’s daughter, Eve Rodriguez Montoya, has also opened a handful of shops that specialize in healthy frozen yogurts with some Mexican-inspired flavors. “Our community is very strong and hard-working – resilient and resourceful,” she said. “I’d say come to our community, get to know our people. Shop at our locations and see for yourself – Little Village is full of people who came to this country to achieve the American Dream.” 

The Rodriguez’s story is just one of many. As more immigrants look to start their own businesses and employ more workers, many markets, both broad and niche, will continue to expand and provide the necessary lift to the recovering economy. 

William Hall is a Business Reporter for [Fox News/MSNBC].

## TWEET UPDATES:

Instead of Breaking News, I think we should put…

NEW REPORT: Immigrant-owned businesses employed over 8 million American workers and generated $1.3 trillion in total sales in 2019, up from 2018 totals according to the latest U.S. Census Bureau data.

This helps to ensure that individuals know that this is the latest data – helps us to not seem ‘dated’ 
