---
title: "Sources of Misperception - Preliminary Analyses"
author: "Patrick Kraft"
date: "January 3, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data, basic sociodemographics

```{r, message=FALSE}
### Packages
library(here)
library(readr)
library(tidyverse)

### Functions
se <- function(x, na.rm = T){
  sd(x, na.rm = na.rm)/sqrt(length(na.omit(x)))
}
cilo <- function(x, na.rm = T){
  mean(x, na.rm = na.rm) - qnorm(.975) * se(x, na.rm)
}
cihi <- function(x, na.rm = T){
  mean(x, na.rm = na.rm) + qnorm(.975) * se(x, na.rm)
}

### Load cleaned data
dat <- read_csv(here("data/immigration_20191219_clean.csv"))
```



# Main analysis


## H1a-H1c: control vs. forced exposure vs. free choice

```{r}
dat %>%
  select(condition, employ, employ_correct, sales, sales_correct, 
         immig_increased, taxes_pos, jobs_pos) %>% 
  gather(variable, value, -condition) %>%
  group_by(condition, variable) %>%
  summarize_all(list(mean = ~mean, cilo = ~cilo, cihi = ~cihi), na.rm = T) %>%
  ggplot(aes(x = mean, xmin = cilo, xmax = cihi, y = condition)) + 
  theme_bw() + labs(y = "Experimental Condition", x = "Average Value") +
  geom_point() + geom_errorbarh(height = 0) + facet_wrap(~variable)
```


### Additional outcomes not measured in control condition

```{r}
dat %>%
  filter(condition != "control") %>%
  select(condition, tweet_click, tweet_time, story_time, 
         actions_discuss, actions_forward, actions_post, actions_seek) %>% 
  gather(variable, value, -condition) %>%
  group_by(condition, variable) %>%
  summarize_all(list(mean = ~mean, cilo = ~cilo, cihi = ~cihi), na.rm = T) %>%
  ggplot(aes(x = mean, xmin = cilo, xmax = cihi, y = condition)) + 
  theme_bw() + labs(y = "Experimental Condition", x = "Average Value") +
  geom_point() + geom_errorbarh(height = 0) + facet_wrap(~variable, scales = "free_x")
```

## H2a-H2c: Determinants of media choice

```{r}
dat %>%
  filter(condition == "choice") %>%
  mutate(prefer_fox = tv_fox - tv_msnbc,
         choose_fox = as.numeric(tweet == "fox")) %>%
  select(choose_fox, ideol_con, pid_rep, prefer_fox) %>%
  gather(variable, value, -choose_fox) %>%
  ggplot(aes(x = value, y = choose_fox)) +
  geom_jitter(alpha = .1, height = .1) + geom_smooth(method = "lm") + 
  facet_grid(~variable, scales = "free_x") +
  theme_bw()
```

