---
title: "Hypothesis Testing"
author: "Jason Neumeyer"
date: "March 4, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Data and Packages - 

```{r, warning=FALSE, message=FALSE}
## Packages

##install.packages("here")
library(here)
##install.packages("readr")
library(readr)
library(tidyverse)
library(ggplot2)
##install.packages("expss")
library(expss)
##install.packages("broom")
library(broom)
##install.packages("purrr")
library(purrr)
##install.packages("stargazer")
library(stargazer)
library(lmtest)
library(MASS)
library(car)

setwd("C:/Users/jason/Desktop/UW-Milwaukee Graduate Year 2/Lab Meeting/Data")

dat <- read_csv("immigration_20191219_clean.csv")

## View(dat)
```


## Preference Variable - 

```{r}
tv_prefer <- dat$tv_msnbc - dat$tv_fox
dat["tv_prefer"] <- tv_prefer
```

# Hypothesis Testing - 

## H2a-c

```{r}
libimm_data <- dat %>% dplyr::select(immig_increased, taxes_pos, jobs_pos, condition, sales_correct, employ_correct)
libimm_data$condition <- as.factor(libimm_data$condition)

libimm <- rowMeans(subset(libimm_data, select = c(immig_increased, taxes_pos, jobs_pos)), na.rm = TRUE)
libimm_data <- cbind(libimm_data, libimm)
libimm_data$libimm <- as.numeric(libimm_data$libimm)


libimm_data$condition <- relevel(libimm_data$condition, ref = "control")

##View(libimm_data)
h1a <- lm(libimm ~ condition, data = libimm_data)
summary(h1a)

h1b <- lm(sales_correct ~ condition, data = libimm_data)
summary(h1b)

h1c <- lm(employ_correct ~ condition, data = libimm_data)
summary(h1c)
```

```{r, results="asis"}
stargazer(h1a, h1b, h1c, dep.var.labels = c("Liberal Immigration Level", "Accurate Sale Numbers", "Accurate Employment Numbers"), covariate.labels = c("Assigned Condition", "Free Choice Condition", "Constant"), title = "Control vs. Free Choice vs. Assigned", header = FALSE)
```

```{r}
lh1 <- linearHypothesis(h1a, c("conditionassigned = conditionchoice"))

lh2 <- linearHypothesis(h1b, c("conditionassigned = conditionchoice"))

lh3 <- linearHypothesis(h1c, c("conditionassigned = conditionchoice"))
```

```{r, results= "asis"}
stargazer(lh1, header = FALSE, title = "Liberal Immigration Level")
stargazer(lh2, header = FALSE, title = "Sales Correct")
stargazer(lh3, header = FALSE, title = "Employ Correct")

```

## H1a-c

```{r}
## Choose Fox

labels_FOX <- c(ideol_con = "Conservative", pid_rep = "Republican", prefer_fox = "Prefer Fox")

choose_fox <- dat %>%
  filter(condition == "choice") %>%
  mutate(prefer_fox = tv_fox - tv_msnbc,
         choose_fox = as.numeric(tweet == "fox")) %>%
  dplyr::select(choose_fox, ideol_con, pid_rep, prefer_fox) %>%
  gather(variable, value, -choose_fox) %>%
  ggplot(aes(x=value, y = choose_fox)) +
  geom_jitter(alpha = .1, height = .1) + geom_smooth(method = "lm") +
  facet_grid(~variable, scales = "free_x", labeller = labeller(variable = labels_FOX)) +
  theme_bw() + labs(y = "Choose FoxNews", x = "")

## Choose MSNBC

ideol_lib <- 1 - dat$ideol_con
dat["ideol_lib"] <- ideol_lib

pid_dem <- 1 - dat$pid_rep
dat["pid_dem"] <- pid_dem

labels_MSNBC <- c(ideol_lib = "Liberal", pid_dem = "Democrat", prefer_msnbc = "Prefer MSNBC")

choose_msnbc <- dat %>%
  filter(condition == "choice") %>%
  mutate(prefer_msnbc = tv_msnbc - tv_fox,
         choose_msnbc = as.numeric(tweet == "msnbc")) %>%
  dplyr::select(choose_msnbc, ideol_lib, pid_dem, prefer_msnbc) %>%
  gather(variable, value, -choose_msnbc) %>%
  ggplot(aes(x=value, y = choose_msnbc)) +
  geom_jitter(alpha = .1, height = .1) + geom_smooth(method = "lm") + 
  facet_grid(~variable, scales = "free_x", labeller = labeller(variable = labels_MSNBC)) + 
  theme_bw() + labs(y = "Choose MSNBC", x = "") 

choose_fox
choose_msnbc

## demographic model for choose FoxNews

choose_fox = as.numeric(dat$tweet == "fox")
prefer_fox <- dat$tv_fox - dat$tv_msnbc

test <- lm(choose_fox ~ prefer_fox + college + white + age, data = dat)
summary(test)

test2 <- lm(choose_fox ~ ideol_con + college + white + age, data = dat)
summary(test2)

test3 <- lm(choose_fox ~ pid_rep + college + white + age, data = dat)
summary(test3)
```

```{r, results='asis'}
stargazer(test, test2, test3, header = FALSE, single.row = T, column.sep.width = "0pt")
```

## H3a-c



